/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SharingModuleStateWithSubscriptionIndexImport } from './routes/sharing-module-state-with-subscription/index'
import { Route as SharingComponentStateWithContextIndexImport } from './routes/sharing-component-state-with-context/index'
import { Route as SharingComponentStateWithContextAndSubscriptionIndexImport } from './routes/sharing-component-state-with-context-and-subscription/index'
import { Route as SharingModuleStateWithSubscriptionWorkingWithUseSyncExternalStoreIndexImport } from './routes/sharing-module-state-with-subscription/working-with-use-sync-external-store/index'
import { Route as SharingModuleStateWithSubscriptionWorkingWithUseSubscriptionIndexImport } from './routes/sharing-module-state-with-subscription/working-with-use-subscription/index'
import { Route as SharingModuleStateWithSubscriptionWorkingWithASelectorIndexImport } from './routes/sharing-module-state-with-subscription/working-with-a-selector/index'
import { Route as SharingComponentStateWithContextSolution2IndexImport } from './routes/sharing-component-state-with-context/solution2/index'
import { Route as SharingComponentStateWithContextSolution1IndexImport } from './routes/sharing-component-state-with-context/solution1/index'
import { Route as SharingComponentStateWithContextFactoryPatternWithACustomHookIndexImport } from './routes/sharing-component-state-with-context/factory-pattern-with-a-custom-hook/index'
import { Route as SharingComponentStateWithContextCreatingCustomHooksAndProviderComponentsIndexImport } from './routes/sharing-component-state-with-context/creating-custom-hooks-and-provider-components/index'
import { Route as SharingComponentStateWithContextAvoidingProviderNestingWithReduceRightIndexImport } from './routes/sharing-component-state-with-context/avoiding-provider-nesting-with-reduce-right/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SharingModuleStateWithSubscriptionIndexRoute =
  SharingModuleStateWithSubscriptionIndexImport.update({
    id: '/sharing-module-state-with-subscription/',
    path: '/sharing-module-state-with-subscription/',
    getParentRoute: () => rootRoute,
  } as any)

const SharingComponentStateWithContextIndexRoute =
  SharingComponentStateWithContextIndexImport.update({
    id: '/sharing-component-state-with-context/',
    path: '/sharing-component-state-with-context/',
    getParentRoute: () => rootRoute,
  } as any)

const SharingComponentStateWithContextAndSubscriptionIndexRoute =
  SharingComponentStateWithContextAndSubscriptionIndexImport.update({
    id: '/sharing-component-state-with-context-and-subscription/',
    path: '/sharing-component-state-with-context-and-subscription/',
    getParentRoute: () => rootRoute,
  } as any)

const SharingModuleStateWithSubscriptionWorkingWithUseSyncExternalStoreIndexRoute =
  SharingModuleStateWithSubscriptionWorkingWithUseSyncExternalStoreIndexImport.update(
    {
      id: '/sharing-module-state-with-subscription/working-with-use-sync-external-store/',
      path: '/sharing-module-state-with-subscription/working-with-use-sync-external-store/',
      getParentRoute: () => rootRoute,
    } as any,
  )

const SharingModuleStateWithSubscriptionWorkingWithUseSubscriptionIndexRoute =
  SharingModuleStateWithSubscriptionWorkingWithUseSubscriptionIndexImport.update(
    {
      id: '/sharing-module-state-with-subscription/working-with-use-subscription/',
      path: '/sharing-module-state-with-subscription/working-with-use-subscription/',
      getParentRoute: () => rootRoute,
    } as any,
  )

const SharingModuleStateWithSubscriptionWorkingWithASelectorIndexRoute =
  SharingModuleStateWithSubscriptionWorkingWithASelectorIndexImport.update({
    id: '/sharing-module-state-with-subscription/working-with-a-selector/',
    path: '/sharing-module-state-with-subscription/working-with-a-selector/',
    getParentRoute: () => rootRoute,
  } as any)

const SharingComponentStateWithContextSolution2IndexRoute =
  SharingComponentStateWithContextSolution2IndexImport.update({
    id: '/sharing-component-state-with-context/solution2/',
    path: '/sharing-component-state-with-context/solution2/',
    getParentRoute: () => rootRoute,
  } as any)

const SharingComponentStateWithContextSolution1IndexRoute =
  SharingComponentStateWithContextSolution1IndexImport.update({
    id: '/sharing-component-state-with-context/solution1/',
    path: '/sharing-component-state-with-context/solution1/',
    getParentRoute: () => rootRoute,
  } as any)

const SharingComponentStateWithContextFactoryPatternWithACustomHookIndexRoute =
  SharingComponentStateWithContextFactoryPatternWithACustomHookIndexImport.update(
    {
      id: '/sharing-component-state-with-context/factory-pattern-with-a-custom-hook/',
      path: '/sharing-component-state-with-context/factory-pattern-with-a-custom-hook/',
      getParentRoute: () => rootRoute,
    } as any,
  )

const SharingComponentStateWithContextCreatingCustomHooksAndProviderComponentsIndexRoute =
  SharingComponentStateWithContextCreatingCustomHooksAndProviderComponentsIndexImport.update(
    {
      id: '/sharing-component-state-with-context/creating-custom-hooks-and-provider-components/',
      path: '/sharing-component-state-with-context/creating-custom-hooks-and-provider-components/',
      getParentRoute: () => rootRoute,
    } as any,
  )

const SharingComponentStateWithContextAvoidingProviderNestingWithReduceRightIndexRoute =
  SharingComponentStateWithContextAvoidingProviderNestingWithReduceRightIndexImport.update(
    {
      id: '/sharing-component-state-with-context/avoiding-provider-nesting-with-reduce-right/',
      path: '/sharing-component-state-with-context/avoiding-provider-nesting-with-reduce-right/',
      getParentRoute: () => rootRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/sharing-component-state-with-context-and-subscription/': {
      id: '/sharing-component-state-with-context-and-subscription/'
      path: '/sharing-component-state-with-context-and-subscription'
      fullPath: '/sharing-component-state-with-context-and-subscription'
      preLoaderRoute: typeof SharingComponentStateWithContextAndSubscriptionIndexImport
      parentRoute: typeof rootRoute
    }
    '/sharing-component-state-with-context/': {
      id: '/sharing-component-state-with-context/'
      path: '/sharing-component-state-with-context'
      fullPath: '/sharing-component-state-with-context'
      preLoaderRoute: typeof SharingComponentStateWithContextIndexImport
      parentRoute: typeof rootRoute
    }
    '/sharing-module-state-with-subscription/': {
      id: '/sharing-module-state-with-subscription/'
      path: '/sharing-module-state-with-subscription'
      fullPath: '/sharing-module-state-with-subscription'
      preLoaderRoute: typeof SharingModuleStateWithSubscriptionIndexImport
      parentRoute: typeof rootRoute
    }
    '/sharing-component-state-with-context/avoiding-provider-nesting-with-reduce-right/': {
      id: '/sharing-component-state-with-context/avoiding-provider-nesting-with-reduce-right/'
      path: '/sharing-component-state-with-context/avoiding-provider-nesting-with-reduce-right'
      fullPath: '/sharing-component-state-with-context/avoiding-provider-nesting-with-reduce-right'
      preLoaderRoute: typeof SharingComponentStateWithContextAvoidingProviderNestingWithReduceRightIndexImport
      parentRoute: typeof rootRoute
    }
    '/sharing-component-state-with-context/creating-custom-hooks-and-provider-components/': {
      id: '/sharing-component-state-with-context/creating-custom-hooks-and-provider-components/'
      path: '/sharing-component-state-with-context/creating-custom-hooks-and-provider-components'
      fullPath: '/sharing-component-state-with-context/creating-custom-hooks-and-provider-components'
      preLoaderRoute: typeof SharingComponentStateWithContextCreatingCustomHooksAndProviderComponentsIndexImport
      parentRoute: typeof rootRoute
    }
    '/sharing-component-state-with-context/factory-pattern-with-a-custom-hook/': {
      id: '/sharing-component-state-with-context/factory-pattern-with-a-custom-hook/'
      path: '/sharing-component-state-with-context/factory-pattern-with-a-custom-hook'
      fullPath: '/sharing-component-state-with-context/factory-pattern-with-a-custom-hook'
      preLoaderRoute: typeof SharingComponentStateWithContextFactoryPatternWithACustomHookIndexImport
      parentRoute: typeof rootRoute
    }
    '/sharing-component-state-with-context/solution1/': {
      id: '/sharing-component-state-with-context/solution1/'
      path: '/sharing-component-state-with-context/solution1'
      fullPath: '/sharing-component-state-with-context/solution1'
      preLoaderRoute: typeof SharingComponentStateWithContextSolution1IndexImport
      parentRoute: typeof rootRoute
    }
    '/sharing-component-state-with-context/solution2/': {
      id: '/sharing-component-state-with-context/solution2/'
      path: '/sharing-component-state-with-context/solution2'
      fullPath: '/sharing-component-state-with-context/solution2'
      preLoaderRoute: typeof SharingComponentStateWithContextSolution2IndexImport
      parentRoute: typeof rootRoute
    }
    '/sharing-module-state-with-subscription/working-with-a-selector/': {
      id: '/sharing-module-state-with-subscription/working-with-a-selector/'
      path: '/sharing-module-state-with-subscription/working-with-a-selector'
      fullPath: '/sharing-module-state-with-subscription/working-with-a-selector'
      preLoaderRoute: typeof SharingModuleStateWithSubscriptionWorkingWithASelectorIndexImport
      parentRoute: typeof rootRoute
    }
    '/sharing-module-state-with-subscription/working-with-use-subscription/': {
      id: '/sharing-module-state-with-subscription/working-with-use-subscription/'
      path: '/sharing-module-state-with-subscription/working-with-use-subscription'
      fullPath: '/sharing-module-state-with-subscription/working-with-use-subscription'
      preLoaderRoute: typeof SharingModuleStateWithSubscriptionWorkingWithUseSubscriptionIndexImport
      parentRoute: typeof rootRoute
    }
    '/sharing-module-state-with-subscription/working-with-use-sync-external-store/': {
      id: '/sharing-module-state-with-subscription/working-with-use-sync-external-store/'
      path: '/sharing-module-state-with-subscription/working-with-use-sync-external-store'
      fullPath: '/sharing-module-state-with-subscription/working-with-use-sync-external-store'
      preLoaderRoute: typeof SharingModuleStateWithSubscriptionWorkingWithUseSyncExternalStoreIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sharing-component-state-with-context-and-subscription': typeof SharingComponentStateWithContextAndSubscriptionIndexRoute
  '/sharing-component-state-with-context': typeof SharingComponentStateWithContextIndexRoute
  '/sharing-module-state-with-subscription': typeof SharingModuleStateWithSubscriptionIndexRoute
  '/sharing-component-state-with-context/avoiding-provider-nesting-with-reduce-right': typeof SharingComponentStateWithContextAvoidingProviderNestingWithReduceRightIndexRoute
  '/sharing-component-state-with-context/creating-custom-hooks-and-provider-components': typeof SharingComponentStateWithContextCreatingCustomHooksAndProviderComponentsIndexRoute
  '/sharing-component-state-with-context/factory-pattern-with-a-custom-hook': typeof SharingComponentStateWithContextFactoryPatternWithACustomHookIndexRoute
  '/sharing-component-state-with-context/solution1': typeof SharingComponentStateWithContextSolution1IndexRoute
  '/sharing-component-state-with-context/solution2': typeof SharingComponentStateWithContextSolution2IndexRoute
  '/sharing-module-state-with-subscription/working-with-a-selector': typeof SharingModuleStateWithSubscriptionWorkingWithASelectorIndexRoute
  '/sharing-module-state-with-subscription/working-with-use-subscription': typeof SharingModuleStateWithSubscriptionWorkingWithUseSubscriptionIndexRoute
  '/sharing-module-state-with-subscription/working-with-use-sync-external-store': typeof SharingModuleStateWithSubscriptionWorkingWithUseSyncExternalStoreIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sharing-component-state-with-context-and-subscription': typeof SharingComponentStateWithContextAndSubscriptionIndexRoute
  '/sharing-component-state-with-context': typeof SharingComponentStateWithContextIndexRoute
  '/sharing-module-state-with-subscription': typeof SharingModuleStateWithSubscriptionIndexRoute
  '/sharing-component-state-with-context/avoiding-provider-nesting-with-reduce-right': typeof SharingComponentStateWithContextAvoidingProviderNestingWithReduceRightIndexRoute
  '/sharing-component-state-with-context/creating-custom-hooks-and-provider-components': typeof SharingComponentStateWithContextCreatingCustomHooksAndProviderComponentsIndexRoute
  '/sharing-component-state-with-context/factory-pattern-with-a-custom-hook': typeof SharingComponentStateWithContextFactoryPatternWithACustomHookIndexRoute
  '/sharing-component-state-with-context/solution1': typeof SharingComponentStateWithContextSolution1IndexRoute
  '/sharing-component-state-with-context/solution2': typeof SharingComponentStateWithContextSolution2IndexRoute
  '/sharing-module-state-with-subscription/working-with-a-selector': typeof SharingModuleStateWithSubscriptionWorkingWithASelectorIndexRoute
  '/sharing-module-state-with-subscription/working-with-use-subscription': typeof SharingModuleStateWithSubscriptionWorkingWithUseSubscriptionIndexRoute
  '/sharing-module-state-with-subscription/working-with-use-sync-external-store': typeof SharingModuleStateWithSubscriptionWorkingWithUseSyncExternalStoreIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/sharing-component-state-with-context-and-subscription/': typeof SharingComponentStateWithContextAndSubscriptionIndexRoute
  '/sharing-component-state-with-context/': typeof SharingComponentStateWithContextIndexRoute
  '/sharing-module-state-with-subscription/': typeof SharingModuleStateWithSubscriptionIndexRoute
  '/sharing-component-state-with-context/avoiding-provider-nesting-with-reduce-right/': typeof SharingComponentStateWithContextAvoidingProviderNestingWithReduceRightIndexRoute
  '/sharing-component-state-with-context/creating-custom-hooks-and-provider-components/': typeof SharingComponentStateWithContextCreatingCustomHooksAndProviderComponentsIndexRoute
  '/sharing-component-state-with-context/factory-pattern-with-a-custom-hook/': typeof SharingComponentStateWithContextFactoryPatternWithACustomHookIndexRoute
  '/sharing-component-state-with-context/solution1/': typeof SharingComponentStateWithContextSolution1IndexRoute
  '/sharing-component-state-with-context/solution2/': typeof SharingComponentStateWithContextSolution2IndexRoute
  '/sharing-module-state-with-subscription/working-with-a-selector/': typeof SharingModuleStateWithSubscriptionWorkingWithASelectorIndexRoute
  '/sharing-module-state-with-subscription/working-with-use-subscription/': typeof SharingModuleStateWithSubscriptionWorkingWithUseSubscriptionIndexRoute
  '/sharing-module-state-with-subscription/working-with-use-sync-external-store/': typeof SharingModuleStateWithSubscriptionWorkingWithUseSyncExternalStoreIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sharing-component-state-with-context-and-subscription'
    | '/sharing-component-state-with-context'
    | '/sharing-module-state-with-subscription'
    | '/sharing-component-state-with-context/avoiding-provider-nesting-with-reduce-right'
    | '/sharing-component-state-with-context/creating-custom-hooks-and-provider-components'
    | '/sharing-component-state-with-context/factory-pattern-with-a-custom-hook'
    | '/sharing-component-state-with-context/solution1'
    | '/sharing-component-state-with-context/solution2'
    | '/sharing-module-state-with-subscription/working-with-a-selector'
    | '/sharing-module-state-with-subscription/working-with-use-subscription'
    | '/sharing-module-state-with-subscription/working-with-use-sync-external-store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sharing-component-state-with-context-and-subscription'
    | '/sharing-component-state-with-context'
    | '/sharing-module-state-with-subscription'
    | '/sharing-component-state-with-context/avoiding-provider-nesting-with-reduce-right'
    | '/sharing-component-state-with-context/creating-custom-hooks-and-provider-components'
    | '/sharing-component-state-with-context/factory-pattern-with-a-custom-hook'
    | '/sharing-component-state-with-context/solution1'
    | '/sharing-component-state-with-context/solution2'
    | '/sharing-module-state-with-subscription/working-with-a-selector'
    | '/sharing-module-state-with-subscription/working-with-use-subscription'
    | '/sharing-module-state-with-subscription/working-with-use-sync-external-store'
  id:
    | '__root__'
    | '/'
    | '/sharing-component-state-with-context-and-subscription/'
    | '/sharing-component-state-with-context/'
    | '/sharing-module-state-with-subscription/'
    | '/sharing-component-state-with-context/avoiding-provider-nesting-with-reduce-right/'
    | '/sharing-component-state-with-context/creating-custom-hooks-and-provider-components/'
    | '/sharing-component-state-with-context/factory-pattern-with-a-custom-hook/'
    | '/sharing-component-state-with-context/solution1/'
    | '/sharing-component-state-with-context/solution2/'
    | '/sharing-module-state-with-subscription/working-with-a-selector/'
    | '/sharing-module-state-with-subscription/working-with-use-subscription/'
    | '/sharing-module-state-with-subscription/working-with-use-sync-external-store/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SharingComponentStateWithContextAndSubscriptionIndexRoute: typeof SharingComponentStateWithContextAndSubscriptionIndexRoute
  SharingComponentStateWithContextIndexRoute: typeof SharingComponentStateWithContextIndexRoute
  SharingModuleStateWithSubscriptionIndexRoute: typeof SharingModuleStateWithSubscriptionIndexRoute
  SharingComponentStateWithContextAvoidingProviderNestingWithReduceRightIndexRoute: typeof SharingComponentStateWithContextAvoidingProviderNestingWithReduceRightIndexRoute
  SharingComponentStateWithContextCreatingCustomHooksAndProviderComponentsIndexRoute: typeof SharingComponentStateWithContextCreatingCustomHooksAndProviderComponentsIndexRoute
  SharingComponentStateWithContextFactoryPatternWithACustomHookIndexRoute: typeof SharingComponentStateWithContextFactoryPatternWithACustomHookIndexRoute
  SharingComponentStateWithContextSolution1IndexRoute: typeof SharingComponentStateWithContextSolution1IndexRoute
  SharingComponentStateWithContextSolution2IndexRoute: typeof SharingComponentStateWithContextSolution2IndexRoute
  SharingModuleStateWithSubscriptionWorkingWithASelectorIndexRoute: typeof SharingModuleStateWithSubscriptionWorkingWithASelectorIndexRoute
  SharingModuleStateWithSubscriptionWorkingWithUseSubscriptionIndexRoute: typeof SharingModuleStateWithSubscriptionWorkingWithUseSubscriptionIndexRoute
  SharingModuleStateWithSubscriptionWorkingWithUseSyncExternalStoreIndexRoute: typeof SharingModuleStateWithSubscriptionWorkingWithUseSyncExternalStoreIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SharingComponentStateWithContextAndSubscriptionIndexRoute:
    SharingComponentStateWithContextAndSubscriptionIndexRoute,
  SharingComponentStateWithContextIndexRoute:
    SharingComponentStateWithContextIndexRoute,
  SharingModuleStateWithSubscriptionIndexRoute:
    SharingModuleStateWithSubscriptionIndexRoute,
  SharingComponentStateWithContextAvoidingProviderNestingWithReduceRightIndexRoute:
    SharingComponentStateWithContextAvoidingProviderNestingWithReduceRightIndexRoute,
  SharingComponentStateWithContextCreatingCustomHooksAndProviderComponentsIndexRoute:
    SharingComponentStateWithContextCreatingCustomHooksAndProviderComponentsIndexRoute,
  SharingComponentStateWithContextFactoryPatternWithACustomHookIndexRoute:
    SharingComponentStateWithContextFactoryPatternWithACustomHookIndexRoute,
  SharingComponentStateWithContextSolution1IndexRoute:
    SharingComponentStateWithContextSolution1IndexRoute,
  SharingComponentStateWithContextSolution2IndexRoute:
    SharingComponentStateWithContextSolution2IndexRoute,
  SharingModuleStateWithSubscriptionWorkingWithASelectorIndexRoute:
    SharingModuleStateWithSubscriptionWorkingWithASelectorIndexRoute,
  SharingModuleStateWithSubscriptionWorkingWithUseSubscriptionIndexRoute:
    SharingModuleStateWithSubscriptionWorkingWithUseSubscriptionIndexRoute,
  SharingModuleStateWithSubscriptionWorkingWithUseSyncExternalStoreIndexRoute:
    SharingModuleStateWithSubscriptionWorkingWithUseSyncExternalStoreIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/sharing-component-state-with-context-and-subscription/",
        "/sharing-component-state-with-context/",
        "/sharing-module-state-with-subscription/",
        "/sharing-component-state-with-context/avoiding-provider-nesting-with-reduce-right/",
        "/sharing-component-state-with-context/creating-custom-hooks-and-provider-components/",
        "/sharing-component-state-with-context/factory-pattern-with-a-custom-hook/",
        "/sharing-component-state-with-context/solution1/",
        "/sharing-component-state-with-context/solution2/",
        "/sharing-module-state-with-subscription/working-with-a-selector/",
        "/sharing-module-state-with-subscription/working-with-use-subscription/",
        "/sharing-module-state-with-subscription/working-with-use-sync-external-store/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/sharing-component-state-with-context-and-subscription/": {
      "filePath": "sharing-component-state-with-context-and-subscription/index.tsx"
    },
    "/sharing-component-state-with-context/": {
      "filePath": "sharing-component-state-with-context/index.tsx"
    },
    "/sharing-module-state-with-subscription/": {
      "filePath": "sharing-module-state-with-subscription/index.tsx"
    },
    "/sharing-component-state-with-context/avoiding-provider-nesting-with-reduce-right/": {
      "filePath": "sharing-component-state-with-context/avoiding-provider-nesting-with-reduce-right/index.tsx"
    },
    "/sharing-component-state-with-context/creating-custom-hooks-and-provider-components/": {
      "filePath": "sharing-component-state-with-context/creating-custom-hooks-and-provider-components/index.tsx"
    },
    "/sharing-component-state-with-context/factory-pattern-with-a-custom-hook/": {
      "filePath": "sharing-component-state-with-context/factory-pattern-with-a-custom-hook/index.tsx"
    },
    "/sharing-component-state-with-context/solution1/": {
      "filePath": "sharing-component-state-with-context/solution1/index.tsx"
    },
    "/sharing-component-state-with-context/solution2/": {
      "filePath": "sharing-component-state-with-context/solution2/index.tsx"
    },
    "/sharing-module-state-with-subscription/working-with-a-selector/": {
      "filePath": "sharing-module-state-with-subscription/working-with-a-selector/index.tsx"
    },
    "/sharing-module-state-with-subscription/working-with-use-subscription/": {
      "filePath": "sharing-module-state-with-subscription/working-with-use-subscription/index.tsx"
    },
    "/sharing-module-state-with-subscription/working-with-use-sync-external-store/": {
      "filePath": "sharing-module-state-with-subscription/working-with-use-sync-external-store/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
