/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UseContextExtraReRenderLimitationsIndexImport } from './routes/use-context-extra-re-render-limitations/index'
import { Route as UseContextExtraReRenderLimitationsSolution2IndexImport } from './routes/use-context-extra-re-render-limitations/solution2/index'
import { Route as UseContextExtraReRenderLimitationsSolution1IndexImport } from './routes/use-context-extra-re-render-limitations/solution1/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UseContextExtraReRenderLimitationsIndexRoute =
  UseContextExtraReRenderLimitationsIndexImport.update({
    id: '/use-context-extra-re-render-limitations/',
    path: '/use-context-extra-re-render-limitations/',
    getParentRoute: () => rootRoute,
  } as any)

const UseContextExtraReRenderLimitationsSolution2IndexRoute =
  UseContextExtraReRenderLimitationsSolution2IndexImport.update({
    id: '/use-context-extra-re-render-limitations/solution2/',
    path: '/use-context-extra-re-render-limitations/solution2/',
    getParentRoute: () => rootRoute,
  } as any)

const UseContextExtraReRenderLimitationsSolution1IndexRoute =
  UseContextExtraReRenderLimitationsSolution1IndexImport.update({
    id: '/use-context-extra-re-render-limitations/solution1/',
    path: '/use-context-extra-re-render-limitations/solution1/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/use-context-extra-re-render-limitations/': {
      id: '/use-context-extra-re-render-limitations/'
      path: '/use-context-extra-re-render-limitations'
      fullPath: '/use-context-extra-re-render-limitations'
      preLoaderRoute: typeof UseContextExtraReRenderLimitationsIndexImport
      parentRoute: typeof rootRoute
    }
    '/use-context-extra-re-render-limitations/solution1/': {
      id: '/use-context-extra-re-render-limitations/solution1/'
      path: '/use-context-extra-re-render-limitations/solution1'
      fullPath: '/use-context-extra-re-render-limitations/solution1'
      preLoaderRoute: typeof UseContextExtraReRenderLimitationsSolution1IndexImport
      parentRoute: typeof rootRoute
    }
    '/use-context-extra-re-render-limitations/solution2/': {
      id: '/use-context-extra-re-render-limitations/solution2/'
      path: '/use-context-extra-re-render-limitations/solution2'
      fullPath: '/use-context-extra-re-render-limitations/solution2'
      preLoaderRoute: typeof UseContextExtraReRenderLimitationsSolution2IndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/use-context-extra-re-render-limitations': typeof UseContextExtraReRenderLimitationsIndexRoute
  '/use-context-extra-re-render-limitations/solution1': typeof UseContextExtraReRenderLimitationsSolution1IndexRoute
  '/use-context-extra-re-render-limitations/solution2': typeof UseContextExtraReRenderLimitationsSolution2IndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/use-context-extra-re-render-limitations': typeof UseContextExtraReRenderLimitationsIndexRoute
  '/use-context-extra-re-render-limitations/solution1': typeof UseContextExtraReRenderLimitationsSolution1IndexRoute
  '/use-context-extra-re-render-limitations/solution2': typeof UseContextExtraReRenderLimitationsSolution2IndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/use-context-extra-re-render-limitations/': typeof UseContextExtraReRenderLimitationsIndexRoute
  '/use-context-extra-re-render-limitations/solution1/': typeof UseContextExtraReRenderLimitationsSolution1IndexRoute
  '/use-context-extra-re-render-limitations/solution2/': typeof UseContextExtraReRenderLimitationsSolution2IndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/use-context-extra-re-render-limitations'
    | '/use-context-extra-re-render-limitations/solution1'
    | '/use-context-extra-re-render-limitations/solution2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/use-context-extra-re-render-limitations'
    | '/use-context-extra-re-render-limitations/solution1'
    | '/use-context-extra-re-render-limitations/solution2'
  id:
    | '__root__'
    | '/'
    | '/use-context-extra-re-render-limitations/'
    | '/use-context-extra-re-render-limitations/solution1/'
    | '/use-context-extra-re-render-limitations/solution2/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UseContextExtraReRenderLimitationsIndexRoute: typeof UseContextExtraReRenderLimitationsIndexRoute
  UseContextExtraReRenderLimitationsSolution1IndexRoute: typeof UseContextExtraReRenderLimitationsSolution1IndexRoute
  UseContextExtraReRenderLimitationsSolution2IndexRoute: typeof UseContextExtraReRenderLimitationsSolution2IndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UseContextExtraReRenderLimitationsIndexRoute:
    UseContextExtraReRenderLimitationsIndexRoute,
  UseContextExtraReRenderLimitationsSolution1IndexRoute:
    UseContextExtraReRenderLimitationsSolution1IndexRoute,
  UseContextExtraReRenderLimitationsSolution2IndexRoute:
    UseContextExtraReRenderLimitationsSolution2IndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/use-context-extra-re-render-limitations/",
        "/use-context-extra-re-render-limitations/solution1/",
        "/use-context-extra-re-render-limitations/solution2/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/use-context-extra-re-render-limitations/": {
      "filePath": "use-context-extra-re-render-limitations/index.tsx"
    },
    "/use-context-extra-re-render-limitations/solution1/": {
      "filePath": "use-context-extra-re-render-limitations/solution1/index.tsx"
    },
    "/use-context-extra-re-render-limitations/solution2/": {
      "filePath": "use-context-extra-re-render-limitations/solution2/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
